all:
	src/run.sh run_all
clone:
	src/run.sh clone
branch:
	src/run.sh co_branch
build:
	src/run.sh build_all
cherry-pick:
	src/run.sh cherry-pick
push:
	src/run.sh push_to_remote
logs:
	src/run.sh git_logs
purge:
	src/run.sh make_purge
reset:
	src/run.sh reset
status:
	src/run.sh make_status
tests:
	src/run.sh tests
abort:
	src/run.sh make_abort
